services:
  mysql:
    container_name: parking-mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1ux2Dewk2xdrk5uqh.CMU
      MYSQL_DATABASE: parking
      TZ: Asia/Shanghai
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app-network

  db-init:
    container_name: parking-db-init
    build: .
    command: python db/init_db.py
    environment:
      MYSQL_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  app:
    container_name: parking-app
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./parking:/code/parking
      - ./static:/code/static
      - ./config:/code/config
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    command: >
      sh -c "
        echo 'Checking environment variables...' &&
        echo 'JWT_SECRET=' &&
        echo $$JWT_SECRET &&
        gunicorn run_api:app --bind 0.0.0.0:8000 --workers 4 --timeout 120
      "

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: